---
- name: 01 nginx install
  become: yes
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: 02 set up nginx config
  become: yes
  template:
    src: templates/flask-app.conf.j2
    dest: /etc/nginx/conf.d/flask-app.conf
    mode: 0644

- name: 03 Start nginx
  become: yes
  ansible.builtin.command:
    cmd: bash -lc "systemctl start nginx.service"


