name: github actions test

on:
  workflow_dispatch:
  push:
    branches:
      - feature/terraform
    paths:
      - .github/workflows/cicd.yml

defaults:
  run:
    shell: bash

env:
  TF_VERSION: 1.11.2

jobs:
  Terraform-Preview:
    name: "Terraform-Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkoup repository
        uses: actions/checkout@v4
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

  # test2:
  #   needs: test1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "test workflow_dispatch"
