name: github actions test

on:
  workflow_dispatch:
  push:
    branches:
      - feature/terraform
    paths:
      - .github/workflows/cicd.yml

defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.11.2
  TF_EXECUTE_PATH: 01_terraform/flask-app/environments/dev/

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Preview:
    name: "Terraform-Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: terraform init
        run: |
          terraform init
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform validate
        run: |
          terraform validate
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform plan
        id: tf-plan
        continue-on-error: true
        run: |
          set +e
          terraform plan \
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'environment=${{ env.TF_ENVIRONMENT }}' \
            -input=false \
        working-directory: ${{ env.TF_EXECUTE_PATH }}
  
  # test2:
  #   needs: test1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "test workflow_dispatch"
      # - name: env check
      #   run: |
      #     echo ${{ vars.ENV_CHECK }}
