name: FLASK_APP_CICD_AWS_dev

on:
  push:
    branches:
      - main
      - feature/serverspec
    paths:
      - .github/workflows/**
      - .trigger/change.txt
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.11.2
  TF_EXECUTE_PATH: 01_terraform/flask-app/environments/dev/

  TF_VAR_project: flask-app
  TF_VAR_environment: dev
  TF_VAR_region: ap-northeast-1
  TF_VAR_ALB_from_IP: ${{ secrets.SEC_01_ALB_FROM_IP }}
  TF_VAR_rds_username: ${{ secrets.RDS_01_RDS_USERNAME }}

  ANS_EXECUTE_PATH: 02_ansible/

  SPEC_EXECUTE_PATH: 03_serverspec/
  SPEC_RUBY_VERSION: 3.2.2

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Preview:
    name: "Terraform-Preview"
    runs-on: ubuntu-latest
    outputs:
      TF_PLAN_EXITCODE: ${{ steps.tf-plan.outputs.TF_PLAN_EXITCODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BED_01_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.BED_02_BACKEND_KEY }}" \
            -backend-config="region="ap-northeast-1""
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform validate
        run: |
          terraform validate
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform plan
        id: tf-plan
        continue-on-error: true
        run: |
          set +e
          terraform plan \
            -input=false \
            -detailed-exitcode
          SET_EXIT_CODE=$?
          echo "TF_PLAN_EXITCODE=$SET_EXIT_CODE" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_EXECUTE_PATH }}

  Terraform-Deploy:
    name: "Terraform-Deploy"
    needs: Terraform-Preview
    if: |
      needs.Terraform-Preview.outputs.TF_PLAN_EXITCODE == '2' ||
      needs.Terraform-Preview.outputs.TF_PLAN_EXITCODE == '0'
    outputs: 
      TF_STATE_FLAG: ${{ steps.tf-flag.outputs.TF_STATE_FLAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BED_01_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.BED_02_BACKEND_KEY }}" \
            -backend-config="region="ap-northeast-1""
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      # - name: terraform apply
      #   run: |
      #     terraform apply -auto-approve
      #   working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform apply
        if: contains(github.event.head_commit.message, '[apply]')
        run: |
          terraform apply -auto-approve
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform destroy
        if: contains(github.event.head_commit.message, '[destroy]')
        run: |
          terraform destroy -auto-approve
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      # terraform state確認フラグ
      # リソースが想定の数構築されているか確認（job Ansible-App-Deployの実行確認）
      - name: terraform state check flag
        id: tf-flag
        run: |
          set +e
          SET_TF_COUNT=$(terraform state list | grep .aws_ | wc -l)
          echo "TF_STATE_FLAG=$SET_TF_COUNT" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      # flagチェック
      - name: check flag
        run: |
          echo ${{ steps.tf-flag.outputs.TF_STATE_FLAG }}
        working-directory: ${{ env.TF_EXECUTE_PATH }}

  Ansible-App-Deploy:
    name: "Ansible-App-Deploy"
    needs: Terraform-Deploy
    if: |
      needs.terraform-Deploy.outputs.TF_STATE_FLAG == '1000'
#      needs.terraform-Deploy.outputs.TF_STATE_FLAG == '56'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Get EC2 instance id
        run: |
          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=flask-app-dev-appsv" \
            "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text > app-i.txt

          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=flask-app-dev-websv" \
            "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text > web-i.txt
        working-directory: ${{ env.ANS_EXECUTE_PATH }}

      - name: Instance id setup in Inventory
        run: |
          sed -i "s/APP-INSTANCE-NUMBER/$(cat app-i.txt)/" inventoryes/hosts.ini
          sed -i "s/WEB-INSTANCE-NUMBER/$(cat web-i.txt)/" inventoryes/hosts.ini
        working-directory: ${{ env.ANS_EXECUTE_PATH }}

      - name: Set SSH Key
        run: |
          echo -e "${{ secrets.EC2_PRIVATE_KEY }}" > GHA-FLASK-APP.pem
          chmod 600 GHA-FLASK-APP.pem
        working-directory: ${{ env.ANS_EXECUTE_PATH }}

      - name: Setup variablesFile
        run: |
          db_host=$(aws ssm get-parameter --with-decryption --query "Parameter.Value" --output text --name /flask-app-dev/DB_HOST)
          db_username=$(aws ssm get-parameter --with-decryption --query "Parameter.Value" --output text --name /flask-app-dev/DB_USERNAME)
          db_userpass=$( aws ssm get-parameter --with-decryption --query "Parameter.Value" --output text --name /flask-app-dev/DB_USERPASS)
          git_user="${{ secrets.SET_GITHUB_USER }}"
          git_token="${{ secrets.SET_GITHUB_TOKEN }}"

          sed -i "s/DB_HOST/${db_host}/" vars/sec.yml
          sed -i "s/DB_USERNAME/${db_username}/" vars/sec.yml
          sed -i "s/DB_USERPASS/${db_userpass}/" vars/sec.yml
          sed -i "s/GITHUB_USER/${git_user}/" vars/sec.yml
          sed -i "s/GITHUB_TOKEN/${git_token}/" vars/sec.yml
        working-directory: ${{ env.ANS_EXECUTE_PATH }}

      - name: Run Ansible-playbook
        run: |
          ansible-playbook -i inventoryes/hosts.ini setup.yml
        working-directory: ${{ env.ANS_EXECUTE_PATH }}

  ServerSpec-Check:
    name: "ServerSpec-Check"
    # needs: Ansible-App-Deploy
    needs: Terraform-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Get EC2 instance id
        run: |
          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=flask-app-dev-appsv" \
            "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text > app-i.txt

          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=flask-app-dev-websv" \
            "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text > web-i.txt
        working-directory: ${{ env.SPEC_EXECUTE_PATH }}

      - name: Instance id setup in helper.rb
        run: |
          sed -i "s/APP-INSTANCE-NUMBER/$(cat app-i.txt)/" spec/spec_helper.rb
          sed -i "s/WEB-INSTANCE-NUMBER/$(cat web-i.txt)/" spec/spec_helper.rb
        working-directory: ${{ env.SPEC_EXECUTE_PATH }}

      - name: Get RDS endpoint name
        run: |
          set +e
          db_host=$(aws ssm get-parameter --with-decryption --query "Parameter.Value" --output text --name /flask-app-dev/DB_HOST)
          echo "RDS-ENDPOINT=$db_host" >> $GITHUB_ENV
        working-directory: ${{ env.SPEC_EXECUTE_PATH }}

      - name: Set SSH Key
        run: |
          echo -e "${{ secrets.EC2_PRIVATE_KEY }}" > GHA-FLASK-APP.pem
          chmod 400 GHA-FLASK-APP.pem
        working-directory: ${{ env.SPEC_EXECUTE_PATH }}

      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.SPEC_RUBY_VERSION }}

      - name: ruby config
        run: |
          gem install bundler
          bundle install
        working-directory: ${{ env.SPEC_EXECUTE_PATH }}

      - name: run server spec
        run: |
          bundle exec rake spec
        working-directory: ${{ env.SPEC_EXECUTE_PATH }}
