name: FLASK_APP_CICD_AWS_dev

on:
  push:
    branches:
      - main
      - feature/ansible
    paths:
      - .github/workflows/**
      - .trigger/change.txt
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.11.2
  TF_EXECUTE_PATH: 01_terraform/flask-app/environments/dev/

  TF_VAR_project: ${{ vars.PRJ_01_PROJECT }}
  TF_VAR_environment: ${{ vars.PRJ_02_ENVIRONMENT }}
  TF_VAR_region: ${{ vars.PRJ_03_REGION }}
  # TF_VAR_backend_bucket: ${{ secrets.BED_01_BACKEND_BUCKET }}
  # TF_VAR_backend_key: ${{ secrets.BED_02_BACKEND_KEY }}
  TF_VAR_ALB_from_IP: ${{ secrets.SEC_01_ALB_FROM_IP }}
  TF_VAR_rds_username: ${{ secrets.RDS_01_RDS_USERNAME }}

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Preview:
    name: "Terraform-Preview"
    runs-on: ubuntu-latest
    outputs:
      TF_PLAN_EXITCODE: ${{ steps.tf-plan.outputs.TF_PLAN_EXITCODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BED_01_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.BED_02_BACKEND_KEY }}" \
            -backend-config="region="ap-northeast-1""
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform validate
        run: |
          terraform validate
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform plan
        id: tf-plan
        continue-on-error: true
        run: |
          set +e
          terraform plan \
            -input=false \
            -detailed-exitcode
          SET_EXIT_CODE=$?
          echo "TF_PLAN_EXITCODE=$SET_EXIT_CODE" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_EXECUTE_PATH }}

  Terraform-Deploy:
    name: "Terraform-Deploy"
    needs: Terraform-Preview
    if: |
      needs.Terraform-Preview.outputs.TF_PLAN_EXITCODE == '2' ||
      needs.Terraform-Preview.outputs.TF_PLAN_EXITCODE == '0'
    outputs: 
      TF_STATE_FLAG: ${{ steps.tf-flag.outputs.TF_STATE_FLAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BED_01_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.BED_02_BACKEND_KEY }}" \
            -backend-config="region="ap-northeast-1""
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      # 正式時は削除
      - name: terraform apply
        if: contains(github.event.head_commit.message, '[apply]')
        run: |
          terraform apply -auto-approve
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      # 正式用
      # - name: terraform apply
      #   run: |
      #     terraform apply -auto-approve
      #   working-directory: ${{ env.TF_EXECUTE_PATH }}

      # 正式時は削除
      - name: terraform destroy
        if: contains(github.event.head_commit.message, '[destroy]')
        run: |
          terraform destroy -auto-approve
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      - name: terraform state check flag
        id: tf-flag
        run: |
          test -z "$(terraform state list 2>/dev/null)" && echo "TF_STATE_FLAG=0" >> $GITHUB_OUTPUT || echo "TF_STATE_FLAG=1" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_EXECUTE_PATH }}

      # flagチェック用
      # 正式時は削除
      - name: check flag
        run: |
          echo ${{ steps.tf-flag.outputs.TF_STATE_FLAG }}
        working-directory: ${{ env.TF_EXECUTE_PATH }}


  Ansible-App-Deploy:
    name: "Ansible-App-Deploy"
    needs: Terraform-Deploy
    if: |
      needs.terraform-Deploy.outputs.TF_STATE_FLAG == '2'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: setup value
        run: |
          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=flask-app-dev-appsv" \
            "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text \
            > app-i.txt
          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=flask-app-dev-websv" \
            "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text \
            > web-i.txt

